# Generated by Django 5.1 on 2024-08-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_is_subscribed_profile_subscription_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_subscribed',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='subscription_end_date',
        ),
    ]
