# Generated by Django 5.1 on 2024-08-22 00:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_quizattempt_date_attempted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
