# Generated by Django 5.1 on 2024-08-22 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_author_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_code',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
