# Generated by Django 5.1 on 2024-08-22 00:30

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_author_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='unique_code',
            field=models.CharField(default=core.models.generate_unique_code, max_length=20, unique=True),
        ),
    ]
