# Generated by Django 5.1 on 2024-08-22 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_author_unique_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionresponse',
            name='is_correct',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='questionresponse',
            name='response_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
