# Generated by Django 5.1 on 2024-08-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pastexampaper_pastexamquestion_explanationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='explanationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('answered', 'Answered')], default='pending', max_length=10),
        ),
    ]
