# Generated by Django 5.1 on 2024-08-22 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_explanationrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastexamquestion',
            name='video_solution',
        ),
        migrations.AddField(
            model_name='pastexamquestion',
            name='video_solution_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for the solution'),
        ),
    ]
