# Generated by Django 5.1 on 2024-08-24 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastexampaper',
            name='image',
            field=models.ImageField(default='default_exam_paper.jpg', upload_to='past_exam_paper_images/'),
        ),
        migrations.AddField(
            model_name='workbook',
            name='image',
            field=models.ImageField(default='default_workbook.png', upload_to='workbook_images/'),
        ),
    ]
